spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: password
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max_wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.studyit.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
      instance-id: dept-8001.com    #默认服务名称的修改
      prefer-ip-address: true                   #IP提示的显示

info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.studyit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: password
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max_wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.studyit.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
      instance-id: dept-8001.com    #默认服务名称的修改
      prefer-ip-address: true                   #IP提示的显示

info:
  app.name: atguigu-microservicecloud-springcloudconfig02
  company.name: www.studyit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$